#define PSI_T_COMMENT                          1
#define PSI_T_LIB                              2
#define PSI_T_QUOTED_STRING                    3
#define PSI_T_EOS                              4
#define PSI_T_TYPEDEF                          5
#define PSI_T_NAME                             6
#define PSI_T_LPAREN                           7
#define PSI_T_RPAREN                           8
#define PSI_T_COMMA                            9
#define PSI_T_VOID                            10
#define PSI_T_INT                             11
#define PSI_T_FLOAT                           12
#define PSI_T_DOUBLE                          13
#define PSI_T_SINT8                           14
#define PSI_T_UINT8                           15
#define PSI_T_SINT16                          16
#define PSI_T_UINT16                          17
#define PSI_T_SINT32                          18
#define PSI_T_UINT32                          19
#define PSI_T_SINT64                          20
#define PSI_T_UINT64                          21
#define PSI_T_LBRACE                          22
#define PSI_T_RBRACE                          23
#define PSI_T_FUNCTION                        24
#define PSI_T_NSNAME                          25
#define PSI_T_COLON                           26
#define PSI_T_NULL                            27
#define PSI_T_DOLLAR                          28
#define PSI_T_REFERENCE                       29
#define PSI_T_EQUALS                          30
#define PSI_T_LET                             31
#define PSI_T_STRVAL                          32
#define PSI_T_INTVAL                          33
#define PSI_T_FLOATVAL                        34
#define PSI_T_BOOLVAL                         35
#define PSI_T_SET                             36
#define PSI_T_TO_STRING                       37
#define PSI_T_TO_INT                          38
#define PSI_T_TO_FLOAT                        39
#define PSI_T_TO_BOOL                         40
#define PSI_T_RET                             41
#define PSI_T_MIXED                           42
#define PSI_T_BOOL                            43
#define PSI_T_STRING                          44
#define PSI_T_ARRAY                           45
#define PSI_T_DIGIT                           46
#define PSI_T_DOT                             47
#define PSI_T_PLUS                            48
#define PSI_T_MINUS                           49
#define PSI_T_POINTER                         50
