#!/usr/bin/env php
# autogenerated file; do not edit
language: c
sudo: required
dist: trusty

addons:
 apt:
  packages:
   - php5-cli
   - php-pear
   - re2c

env:
 matrix:
<?php

$gen = include __DIR__."/../travis/pecl/gen-matrix.php";
$env = $gen([
	"PHP" => ["7.0", "7.1", "master"],
	"enable_debug",
	#"enable_maintainer_zts",
	"enable_psi" => ["yes"],
	"enable_psi_posix" => ["all"]
]);
foreach ($env as $e) {
	printf("  - %s\n", $e);
}

?>

before_script:
 - make -f travis/pecl/Makefile php
 - make -f travis/pecl/Makefile ext PECL=psi

script:
 - make -f travis/pecl/Makefile test

