#define PSI_T_BOOL                             1
#define PSI_T_INT                              2
#define PSI_T_FLOAT                            3
#define PSI_T_STRING                           4
#define PSI_T_DOUBLE                           5
#define PSI_T_INT8                             6
#define PSI_T_UINT8                            7
#define PSI_T_INT16                            8
#define PSI_T_UINT16                           9
#define PSI_T_INT32                           10
#define PSI_T_UINT32                          11
#define PSI_T_INT64                           12
#define PSI_T_UINT64                          13
#define PSI_T_NAME                            14
#define PSI_T_NULL                            15
#define PSI_T_NUMBER                          16
#define PSI_T_TRUE                            17
#define PSI_T_FALSE                           18
#define PSI_T_QUOTED_STRING                   19
#define PSI_T_NSNAME                          20
#define PSI_T_PIPE                            21
#define PSI_T_CARET                           22
#define PSI_T_AMPERSAND                       23
#define PSI_T_LSHIFT                          24
#define PSI_T_RSHIFT                          25
#define PSI_T_PLUS                            26
#define PSI_T_MINUS                           27
#define PSI_T_ASTERISK                        28
#define PSI_T_SLASH                           29
#define PSI_T_MODULO                          30
#define PSI_T_TILDE                           31
#define PSI_T_NOT                             32
#define PSI_T_ZVAL                            33
#define PSI_T_OBJVAL                          34
#define PSI_T_ARRVAL                          35
#define PSI_T_PATHVAL                         36
#define PSI_T_STRLEN                          37
#define PSI_T_STRVAL                          38
#define PSI_T_FLOATVAL                        39
#define PSI_T_INTVAL                          40
#define PSI_T_BOOLVAL                         41
#define PSI_T_COUNT                           42
#define PSI_T_TO_OBJECT                       43
#define PSI_T_TO_ARRAY                        44
#define PSI_T_TO_STRING                       45
#define PSI_T_TO_INT                          46
#define PSI_T_TO_FLOAT                        47
#define PSI_T_TO_BOOL                         48
#define PSI_T_VOID                            49
#define PSI_T_MIXED                           50
#define PSI_T_ARRAY                           51
#define PSI_T_OBJECT                          52
#define PSI_T_CALLABLE                        53
#define PSI_T_TEMP                            54
#define PSI_T_FREE                            55
#define PSI_T_SET                             56
#define PSI_T_LET                             57
#define PSI_T_RETURN                          58
#define PSI_T_CALLOC                          59
#define PSI_T_CALLBACK                        60
#define PSI_T_LIB                             61
#define PSI_T_EOF                             62
#define PSI_T_EOS                             63
#define PSI_T_COLON                           64
#define PSI_T_LPAREN                          65
#define PSI_T_COMMA                           66
#define PSI_T_RPAREN                          67
#define PSI_T_ENUM                            68
#define PSI_T_STRUCT                          69
#define PSI_T_UNION                           70
#define PSI_T_LBRACE                          71
#define PSI_T_RBRACE                          72
#define PSI_T_EQUALS                          73
#define PSI_T_CONST                           74
#define PSI_T_TYPEDEF                         75
#define PSI_T_ELLIPSIS                        76
#define PSI_T_LBRACKET                        77
#define PSI_T_RBRACKET                        78
#define PSI_T_CHAR                            79
#define PSI_T_SHORT                           80
#define PSI_T_LONG                            81
#define PSI_T_UNSIGNED                        82
#define PSI_T_SIGNED                          83
#define PSI_T_STATIC                          84
#define PSI_T_FUNCTION                        85
#define PSI_T_DOLLAR_NAME                     86
