#define PSI_T_NAME                             1
#define PSI_T_FREE                             2
#define PSI_T_SET                              3
#define PSI_T_LET                              4
#define PSI_T_RETURN                           5
#define PSI_T_LIB                              6
#define PSI_T_INT                              7
#define PSI_T_QUOTED_STRING                    8
#define PSI_T_EOS                              9
#define PSI_T_STRUCT                          10
#define PSI_T_LBRACE                          11
#define PSI_T_RBRACE                          12
#define PSI_T_COLON                           13
#define PSI_T_LPAREN                          14
#define PSI_T_NUMBER                          15
#define PSI_T_RPAREN                          16
#define PSI_T_BOOL                            17
#define PSI_T_FLOAT                           18
#define PSI_T_STRING                          19
#define PSI_T_CONST                           20
#define PSI_T_NSNAME                          21
#define PSI_T_EQUALS                          22
#define PSI_T_TYPEDEF                         23
#define PSI_T_VOID                            24
#define PSI_T_LBRACKET                        25
#define PSI_T_RBRACKET                        26
#define PSI_T_COMMA                           27
#define PSI_T_DOUBLE                          28
#define PSI_T_INT8                            29
#define PSI_T_UINT8                           30
#define PSI_T_INT16                           31
#define PSI_T_UINT16                          32
#define PSI_T_INT32                           33
#define PSI_T_UINT32                          34
#define PSI_T_INT64                           35
#define PSI_T_UINT64                          36
#define PSI_T_FUNCTION                        37
#define PSI_T_REFERENCE                       38
#define PSI_T_NULL                            39
#define PSI_T_TRUE                            40
#define PSI_T_FALSE                           41
#define PSI_T_DOLLAR                          42
#define PSI_T_CALLOC                          43
#define PSI_T_ARRVAL                          44
#define PSI_T_STRLEN                          45
#define PSI_T_STRVAL                          46
#define PSI_T_FLOATVAL                        47
#define PSI_T_INTVAL                          48
#define PSI_T_BOOLVAL                         49
#define PSI_T_TO_ARRAY                        50
#define PSI_T_TO_STRING                       51
#define PSI_T_TO_INT                          52
#define PSI_T_TO_FLOAT                        53
#define PSI_T_TO_BOOL                         54
#define PSI_T_MIXED                           55
#define PSI_T_ARRAY                           56
#define PSI_T_POINTER                         57
