#define PSI_T_COMMENT                          1
#define PSI_T_LIB                              2
#define PSI_T_QUOTED_STRING                    3
#define PSI_T_EOS                              4
#define PSI_T_BOOL                             5
#define PSI_T_INT                              6
#define PSI_T_FLOAT                            7
#define PSI_T_STRING                           8
#define PSI_T_CONST                            9
#define PSI_T_NSNAME                          10
#define PSI_T_EQUALS                          11
#define PSI_T_TYPEDEF                         12
#define PSI_T_NAME                            13
#define PSI_T_LPAREN                          14
#define PSI_T_RPAREN                          15
#define PSI_T_LBRACKET                        16
#define PSI_T_NUMBER                          17
#define PSI_T_RBRACKET                        18
#define PSI_T_DIGITS                          19
#define PSI_T_COMMA                           20
#define PSI_T_VOID                            21
#define PSI_T_CHAR                            22
#define PSI_T_SHORT                           23
#define PSI_T_LONG                            24
#define PSI_T_DOUBLE                          25
#define PSI_T_SINT8                           26
#define PSI_T_UINT8                           27
#define PSI_T_SINT16                          28
#define PSI_T_UINT16                          29
#define PSI_T_SINT32                          30
#define PSI_T_UINT32                          31
#define PSI_T_SINT64                          32
#define PSI_T_UINT64                          33
#define PSI_T_LBRACE                          34
#define PSI_T_RBRACE                          35
#define PSI_T_FUNCTION                        36
#define PSI_T_COLON                           37
#define PSI_T_REFERENCE                       38
#define PSI_T_NULL                            39
#define PSI_T_TRUE                            40
#define PSI_T_FALSE                           41
#define PSI_T_DOLLAR                          42
#define PSI_T_LET                             43
#define PSI_T_STRLEN                          44
#define PSI_T_STRVAL                          45
#define PSI_T_INTVAL                          46
#define PSI_T_FLOATVAL                        47
#define PSI_T_BOOLVAL                         48
#define PSI_T_SET                             49
#define PSI_T_TO_STRING                       50
#define PSI_T_TO_INT                          51
#define PSI_T_TO_FLOAT                        52
#define PSI_T_TO_BOOL                         53
#define PSI_T_RETURN                          54
#define PSI_T_FREE                            55
#define PSI_T_MIXED                           56
#define PSI_T_ARRAY                           57
#define PSI_T_POINTER                         58
